# fly.toml app configuration file generated for lunch-api on 2023-06-24T22:42:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lunch-api"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
